version: '3'

services:
  authenticator:
    image: authenticator:1.0
    ports: 
      - "8085:8085"
    deploy:
      resources:
        limits:
          memory: 60m
    volumes:
      - '../config/authenticator/:/graduation-thesis/config/authenticator/'
    restart: unless-stopped
