FROM golang:1.21-alpine3.17

WORKDIR /graduation-thesis

COPY ./go.mod ./go.sum ./
RUN go mod download

RUN mkdir -p cmd/message
RUN mkdir -p internal/message
RUN mkdir -p pkg
RUN mkdir -p config/message

COPY ./cmd/message/main.go ./cmd/message
COPY ./internal/message ./internal/message
COPY ./pkg ./pkg
COPY ./config/message/config.yaml ./config/message

RUN CGO_ENABLED=0 GOOS=linux go build -o /message cmd/message/main.go

EXPOSE 8080

CMD ["/message"]