FROM golang:1.21-alpine3.17

WORKDIR /graduation-thesis

COPY ./go.mod ./go.sum ./
RUN go mod download

RUN mkdir -p cmd/asset
RUN mkdir -p internal/asset
RUN mkdir -p pkg
RUN mkdir -p config/asset
RUN mkdir -p local
RUN mkdir -p log/asset
RUN touch log/asset/info.log

COPY ./cmd/asset/main.go ./cmd/asset
COPY ./internal/asset ./internal/asset
COPY ./pkg ./pkg
RUN rm -rf ./pkg/storage/kafkaConsumer.go && rm -rf ./pkg/storage/kafkaProducer.go
COPY ./config/asset/config.yaml ./config/asset

RUN CGO_ENABLED=0 GOOS=linux go build -o main cmd/asset/main.go

# EXPOSE 8080

CMD ["./main"]