version: '3'
services:
  kafka:
    image: confluentinc/cp-server:6.0.14
    depends_on:
      - zookeeper
    ports:
      - '29092:9092'
    deploy:
      resources:
        limits:
          memory: 500m
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://kafka:29092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_HEAP_OPTS: '-Xmx512M -Xms512M'
      # KAFKA_BROKER_ID: 1
      # KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://kafka:29092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      # # KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      # # KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 1000
      # # KAKFAconfluent-telemetry-metrics
      # CONTROL_CENTER_METRICS_TOPIC_REPLICATION: 1
      # KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_CONFLUENT_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # # KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:9092
      # # KAFKA_CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      # KAFKA_CONFLUENT_METRICS_ENABLE: false
      # # KAFKA_CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
      # # KAFKA_CONFLUENT_BALANCER_HEAL_UNEVEN_LOAD_TRIGGER: ANY_UNEVEN_LOAD
      # # KAFKA_CONFLUENT_BALANCER_HEAL_BROKER_FAILURE_THRESHOLD_MS: 5000
      # KAFKA_CONFLUENT_BALANCER_ENABLE: false
      # KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # # KAFKA_NUM_PARTITIONS: 4
      # KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      
  # kafka2:
  #   image: confluentinc/cp-server:6.0.14
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - '29093:29093' # Adjust port number as needed
  #   environment:
  #     KAFKA_BROKER_ID: 2 # Change the broker ID
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #     KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:9092,LISTENER_DOCKER_EXTERNAL://localhost:29093
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
  #     # Thu thap du lieu cac node
  #     KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter 
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 2
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
  #     KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:9092 # node giu cac metrics
  #     KAFKA_CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
  #     KAFKA_CONFLUENT_METRICS_ENABLE: 'true' # Bat thu thap metrics
  #     KAFKA_CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
  #     KAFKA_CONFLUENT_BALANCER_HEAL_UNEVEN_LOAD_TRIGGER: ANY_UNEVEN_LOAD # DKien de can bang partition
  #     KAFKA_CONFLUENT_BALANCER_HEAL_BROKER_FAILURE_THRESHOLD_MS: 5000
  #     KAFKA_CONFLUENT_BALANCER_ENABLE: 'false' # Khong tu dong can bang partition
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  #     # KAFKA_NUM_PARTITIONS: 4
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  
  # kafka3:
  #   image: confluentinc/cp-server:6.0.14
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - '29094:29094' # Adjust port number as needed
  #   environment:
  #     KAFKA_BROKER_ID: 3 # Change the broker ID
  #     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  #     KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:9092,LISTENER_DOCKER_EXTERNAL://localhost:29094
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
  #     KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 2
  #     KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 28
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
  #     KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:9092
  #     KAFKA_CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 2
  #     KAFKA_CONFLUENT_METRICS_ENABLE: 'true'
  #     KAFKA_CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
  #     KAFKA_CONFLUENT_BALANCER_HEAL_UNEVEN_LOAD_TRIGGER: ANY_UNEVEN_LOAD
  #     KAFKA_CONFLUENT_BALANCER_HEAL_BROKER_FAILURE_THRESHOLD_MS: 5000
  #     KAFKA_CONFLUENT_BALANCER_ENABLE: 'false'
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  #     # KAFKA_NUM_PARTITIONS: 4
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  # kafka-ui:
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #     - 8085:8080
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092, kafka2:9092
  #     DYNAMIC_CONFIG_ENABLED: 'true'
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.14
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

