version: '3'

services:
  user_service:
    image: user_service:1.0
    ports: 
      - "8098:8098"
    deploy:
      resources:
        limits:
          memory: 60m
    volumes:
      - '../config/user/:/graduation-thesis/config/user/'
  
  group_service:
    image: group_service:1.0
    ports: 
      - "809:8099"
    deploy:
      resources:
        limits:
          memory: 60m
    volumes:
      - '../config/group/:/graduation-thesis/config/group/'