version: '3'

services:
  websocket_manager:
    image: websocket_manager:1.0
    ports: 
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 60m
    volumes:
      - '../config/websocket_manager/:/graduation-thesis/config/websocket_manager/'
  websocket_handler:
    image: websocket_handler:1.0
    ports: 
      - "8081:8081"
    volumes:
      - '../config/websocket_handler/:/graduation-thesis/config/websocket_handler/'
    deploy:
      resources:
        limits:
          memory: 60m