app:
  port: 8093
  # local_dir: D:\\go\\src\\graduation-thesis\\config\\asset
  local_dir: ./local

logger:
  level: debug
  path: ./log/asset/info.log

seaweed:
  master_url: http://localhost:9333
  volume_url: http://localhost:8080