postgres:
  url: "host=192.168.77.112 port=5432 user=postgres password=Pa$w0rd dbname=graduation_thesis sslmode=disable application_name=user_service"

redis:
  url: redis://192.168.77.112:6379/0

token:
  at_expires: 60*15 # 15 mins
  rt_expires: 60*60*24 # 1 day
  access_secret: 4cC3Ss_s3CrEt
  refresh_secret: tErC3s_hS3rfer

app:
  port: 8098
