app:
  port: 8081
id: 1
fetch_interval: 60
ping_interval: 5
max_retries: 5
retry_interval: 1
cache_timeout: 30

logger:
  level: debug
  path: ./log/websocket_handler/info.log

kafka:
  bootstrap_server: deployments-kafka-1:9092
  message_max_bytes: 10000000
  topic: websocket_connection

3rd_party:
  group_service_url: http://deployments-websocket_manager-1:8080
  message_service_url: http://deployments-websocket_manager-1:8080
  websocket_manager_url: http://deployments-websocket_manager-1:8080/v1/websocket_handler
  