app:
  https_port: 8081
  http_port: 18081
  key:
  cert: 
id: 1
fetch_interval: 60s
ping_interval: 5s
max_retries: 5
retry_interval: 1s
cache_timeout: 30s

logger:
  level: debug
  path: ./log/websocket_handler/info.log

kafka:
  bootstrap_server: kafka:9092
  message_max_bytes: 10000000
  topic: websocket_connection

3rd_party:
  group_service_url: http://group_service:18099/v1
  message_service_url: http://message_service:18090/v1
  websocket_manager_url: http://websocket_manager:8080/v1
  authenticator_url: http://authenticator:8085/v1/validate
  