cassandra:
  hosts: ["cassandra-1:9042"]
  keyspace: graduation_thesis

kafka:
  bootstrap_server: kafka:9092
  message_max_bytes: 10000000
  topic: messages

logger:
  level: debug
  path: ./log/message/info.log

app:
  port: 8090