cassandra:
  hosts: ["cassandra-1:9042"]
  keyspace: graduation_thesis

kafka:
  bootstrap_servers: kafka:9092
  message_max_bytes: 10000000
  topic: messages

logger:
  level: debug
  path: ./log/message/info.log

group_service_url: http://group_service:8099/v1

app:
  port: 8090