app:
  port: 8099

postgre:
  url: "host=postgres port=5432 user=postgres password=Pa$$w0rd dbname=graduation_thesis sslmode=disable application_name=group_service"

redis:
  url: redis://localhost:6379/0